name: digital_orientation
description: A new Flutter project for SmartKids Series

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # ✅ Declare ENTIRE folders to include ALL contents recursively
    # This ensures all images, HTML, JS, CSS, and other assets are included
    
    # All images (covers everything in images/ folder recursively)
    - assets/images/
    
    # All audio files
    - assets/audio/
    
    # All icons
    - assets/icons/
    
    # ✅ CRITICAL: Entire HTML folders for all series (includes ALL files recursively)
    # This will include ALL Captivate projects with their assets, JS, CSS, images, etc.
    - assets/html/