name: digital_orientation
description: A new Flutter project for SmartKids Series

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  path_provider: ^2.1.2
  url_launcher: ^6.1.11
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # Logo
    - assets/images/splash/logo.png

    # Root asset directories (Flutter will include everything inside)
    - assets/images/
    - assets/audio/
    - assets/icons/
    - assets/html/
