name: digital_orientation
description: A new Flutter project for SmartKids Series

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.10.0
  path_provider: ^2.1.2
  url_launcher: ^6.1.11
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:

    - assets/images/splash/
    
    # ================= SMARTKIDS SERIES =================
    - assets/html/sk/paperback_textbook/eng_pg/index.html
    - assets/html/sk/paperback_workbooks/
    - assets/html/sk/soft_form_worksheets/
    - assets/html/sk/classroom_interactive_app/
    - assets/html/sk/home_interactive_app/
    - assets/html/sk/auto_paper_generator/

    # ================= READIFY SERIES =================
    - assets/html/rf/paperback_textbooks/
    - assets/html/rf/soft_form_worksheets/
    - assets/html/rf/home_interactive_app/
    - assets/html/rf/auto_paper_generator/

    # ================= ABBASI SERIES =================
    - assets/html/ab/paperback_textbooks/
    - assets/html/ab/soft_form_key_books/
    - assets/html/ab/auto_paper_generator/

    # ================= AERI SERIES =================
    - assets/html/ai/paperback_textbooks/
    - assets/html/ai/soft_form_key_books/
    - assets/html/ai/auto_paper_generator/
